export { default as Logo } from "./Logo.svg";
export { default as AddImage } from "./Add Image.svg";
export { default as AgeIcon } from "./AgeIcon.svg";
export { default as Agree } from "./Agree.svg";
export { default as Airplane } from "./Airplane.svg";
export { default as Alarm } from "./Alarm.svg";
export { default as Axe } from "./Axe.svg";
export { default as Camera } from "./Camera.svg";
export { default as Create } from "./Create.svg";
export { default as Dashboard } from "./Circled Menu.svg";
export { default as Drawing } from "./Drawing.svg";
export { default as Favorite } from "./Favorite.svg";
export { default as Favorite2 } from "./Favorite2.svg";
export { default as Filter } from "./Filter.svg";
export { default as Gear } from "./Gear.svg";
export { default as GenderIcon } from "./GenderIcon.svg";
export { default as Heart } from "./Heart.svg";
export { default as Height } from "./Height.svg";
export { default as History } from "./History.svg";
export { default as Location } from "./Location.svg";
export { default as MaleUser } from "./Male User.svg";
export { default as Menu } from "./Menu.svg";
export { default as MountainBiking } from "./Mountain Biking.svg";
export { default as Museum } from "./Museum.svg";
export { default as Nationality } from "./Nationality.svg";
export { default as Needle } from "./Needle.svg";
export { default as PaidBill } from "./Paid Bill.svg";
export { default as PlusIcon } from "./PlusIcon.svg";
export { default as Quill } from "./Quill.svg";
export { default as RelationshipIcon } from "./RelationshipIcon.svg";
export { default as Religion } from "./Religion.svg";
export { default as RiceBowl } from "./Rice Bowl.svg";
export { default as Romance } from "./Romance.svg";
export { default as Search } from "./Search.svg";
export { default as ArrowDown } from "./shape.svg";
export { default as Shutdown } from "./Shutdown.svg";
export { default as Tango } from "./Tango.svg";
export { default as TravelAgent } from "./travel-agent.svg";
export { default as Umbrella } from "./Umbrella.svg";
export { default as Verified } from "./Verified.svg";
export { default as Weight } from "./Weight.svg";
export { default as Work } from "./Work.svg";
export { default as DavinaAvatar } from "./davinaAvatar.svg";
export { default as EmilyAvatar } from "./emilyAvatar.svg";
export { default as JohnAvatar } from "./johnAvatar.svg";
export { default as MadsAvatar } from "./madsAvatar.svg";
export { default as LoveAvatar } from "./loveAvatar.svg";
export { default as KarenAvatar } from "./karenAvatar.svg";
export { default as SharonAvatar } from "./sharonAvatar.svg";
export { default as KevinAvatar } from "./kevinAvatar.svg";
export { default as LilyAvatar } from "./lilyAvatar.svg";
export { default as DavonAvatar } from "./davonAvatar.svg";
export { default as VivianAvatar } from "./vivianAvatar.svg";
export { default as JackAvatar } from "./jackAvatar.svg";
export { default as DaveAvatar } from "./daveAvatar.svg";
export { default as Pencil } from "./Pencil.svg";
